// packages/live-preview-react/src/caisy-connection-indicator/CaisyConnectionIndicator.tsx
import { createCaisyConnectionIndicator } from "@nicolasshiken/live-preview-javascript/createCaisyConnectionIndicator";
import { FC, useEffect } from "react";
import "@nicolasshiken/live-preview-javascript/indicatorStyles";
import "@nicolasshiken/live-preview-javascript/styles";

export const CaisyConnectionIndicator: FC = () => {
  useEffect(() => {
    if (typeof window === "undefined") return;

    const { observer, connectionIndicator } = createCaisyConnectionIndicator();

    document.body.append(connectionIndicator);

    return () => {
      observer.disconnect();
      connectionIndicator.remove();
    };
  }, []);

  return null;
};

// packages/live-preview-vue/src/caisy-connection-indicator/CaisyConnectionIndicator.vue
<script setup>
import "@nicolasshiken/live-preview-javascript/indicatorStyles";
import "@nicolasshiken/live-preview-javascript/styles";
import { createCaisyConnectionIndicator } from "@nicolasshiken/live-preview-javascript/createCaisyConnectionIndicator";
import { onMounted, onUnmounted } from "vue";

let connectionIndicator, observer;

onMounted(() => {
  const createdIndicator = createCaisyConnectionIndicator();
  connectionIndicator = createdIndicator.connectionIndicator;
  observer = createdIndicator.observer;
  document.body.append(connectionIndicator);
});

onUnmounted(() => {
  observer.disconnect();
  connectionIndicator.remove();
});
</script>

<template></template>
